#!/usr/bin/env python3
"""Validate the static project package."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REQUIRED_FILES = [
    "index.html",
    "src/app.js",
    "src/styles.css",
    "data/corpus.json",
    "data/live_corpus.json",
    "README.md",
    "LICENSE",
    "docs/engines.md",
    "docs/replication_package.md",
    "docs/data_dictionary.md",
    "docs/roadmap.md",
    "docs/demo_guide.md",
    "docs/analyst_schema.md",
    "docs/course_methods_map.md",
    "docs/source_processing.md",
    "report/project_report.md",
    "scripts/build_corpus.py",
    "scripts/fetch_live_sources.py",
    "server/llm_relay.py",
    "server/data_relay.py",
    ".env.example",
]


def fail(message: str) -> None:
    print(f"FAIL: {message}", file=sys.stderr)
    raise SystemExit(1)


def run(command: list[str]) -> None:
    subprocess.run(command, cwd=ROOT, check=True)


def validate_files() -> None:
    for rel in REQUIRED_FILES:
        path = ROOT / rel
        if not path.exists():
            fail(f"missing {rel}")
        if path.is_file() and path.stat().st_size == 0 and rel != ".nojekyll":
            fail(f"empty {rel}")


def validate_json() -> None:
    for rel, minimum in [("data/corpus.json", 100), ("data/live_corpus.json", 1)]:
        data = json.loads((ROOT / rel).read_text())
        if len(data) < minimum:
            fail(f"{rel} has only {len(data)} documents")
        required = {
            "id",
            "date",
            "source_type",
            "speaker",
            "organization",
            "party",
            "ticker",
            "title",
            "source_url",
            "text",
        }
        for item in data:
            if set(item) != required:
                fail(f"{rel} schema mismatch in {item.get('id', '<missing id>')}")


def validate_copy() -> None:
    haystack = "\n".join(
        (ROOT / rel).read_text(errors="replace")
        for rel in [
            "index.html",
            "README.md",
            "docs/engines.md",
            "docs/replication_package.md",
            "report/project_report.md",
            "src/app.js",
        ]
    )
    banned = ["Course Project", "Text as Data Course Project", "Codex", "ChatGPT", "generated by"]
    for term in banned:
        if re.search(re.escape(term), haystack, re.I):
            fail(f"banned visible phrase remains: {term}")


def main() -> None:
    validate_files()
    validate_json()
    validate_copy()
    run(["node", "--check", "src/app.js"])
    run(["python3", "-m", "py_compile", "scripts/build_corpus.py", "scripts/fetch_live_sources.py", "server/llm_relay.py", "server/data_relay.py"])
    print("project validation passed")


if __name__ == "__main__":
    main()
